# Generated by Django 5.1.3 on 2025-08-24 09:16

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="document",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx", "txt", "jpg", "png"]
                    )
                ],
                verbose_name="document",
            ),
        ),
    ]
