# Generated by Django 5.1.3 on 2025-08-24 10:09

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
                verbose_name="image",
            ),
        ),
    ]
